apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: airflow
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: airflow-postgresql
  POSTGRES_DB: testme
